config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :seasons
  devise_for :admins, controllers: { omniauth_callbacks: "omniauth" }
  devise_scope :admin do
    get "sign_in", to: "auth#sign_in", as: :new_admin_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_admin_session
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  PagesController::PAGES.each do |path|
    get path.dasherize, to: "pages##{path}", as: path.to_sym
  end

  get "admin", to: "admin#index", as: :admin

  resources :bike_rentals, except: :show do
    member { patch :move }
  end
  resources :carousels, only: %i[index show]
  resources :faqs, except: :show do
    member { patch :move }
  end
  resources :galleries
  resources :guides, except: :show do
    member { patch :move }
  end
  resources :page_text, only: :update
  resources :partners do
    member { patch :move }
  end
  resources :photos, except: %i[index show] do
    member { patch :move }
  end
  resources :testimonials, except: :show do
    member { patch :move }
  end

  # redirects
  get "bike-rental", to: redirect("/bike_rentals")
  get "login", to: redirect("/sign_in")
end

app/models/faq.rb
# frozen_string_literal: true

class Faq < ApplicationRecord
  acts_as_list top_of_list: 0
  audited

  validates :question, presence: true
  validates :answer, presence: true

  scope :ordered, -> { order :position }
end

app/controllers/faqs_controller.rb
# frozen_string_literal: true

class FaqsController < ApplicationController
  include Moveable

  before_action :authenticate_admin!, except: :index
  before_action :set_faq, only: %i[edit update destroy move]

  def index
    @faqs = Faq.ordered
  end

  def new
    @faq = Faq.new
  end

  def edit; end

  def create
    @faq = Faq.new(faq_params)

    if @faq.save
      redirect_to faqs_path, notice: t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @faq.update(faq_params)
      redirect_to faqs_path, notice: t(".success"), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @faq.destroy!

    redirect_to faqs_path, notice: t(".success"), status: :see_other
  end

  def move
    super(@faq)
  end

  private

  def set_faq
    @faq = Faq.find params[:id]
  end

  def faq_params
    params.expect(faq: %i[question answer])
  end
end

app/views/faqs/_faq.html.erb
<div class="accordion-item" id="<%= dom_id faq %>" data-sortable-url="<%= move_faq_path faq %>">
  <h2 class="accordion-header row">
    <div class="col">
      <button class="accordion-button collapsed" id="question-<%= faq.id %>" type="button"
              data-bs-toggle="collapse" data-bs-target="#answer-<%= faq.id %>"
              aria-expanded="true" aria-controls="#collapse-<%= faq.id %>">
        <% if admin_signed_in? %>
          <%= fa_icon "grip-lines", class: "me-2 sortable-handle" %>
        <% end %>
        <%= faq.question %>
      </button>
    </div>
    <% if admin_signed_in? %>
      <div class="col-sm-2 col-lg-1 align-self-center">
        <%= link_to edit_faq_path(faq), class: %i[btn btn-secondary], title: t(".edit") do %>
          <%= fa_icon "pencil" %>
        <% end %>
      </div>
    <% end %>
  </h2>

  <div id="answer-<%= faq.id %>" class="accordion-collapse collapse" aria-labelledby="question-<%= faq.id %>"
       data-bs-parent="#faqs">
    <div class="accordion-body">
      <%= sanitize faq.answer %>
    </div>
  </div>
</div>

app/views/faqs/_form.html.erb
<%= bootstrap_form_with(model: faq, data: { controller: :tinymce }) do |form| %>
  <% if faq.errors.any? %>
    <div style="color: red">
      <h2><%= t ".errors", count: faq.errors.count %></h2>

      <ul>
        <% faq.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :question %>
  <%= form.text_area :answer, data: { tinymce_target: :input }, required: false %>

  <div>
    <%= form.submit %>
    <% if faq.persisted? %>
      <%= link_to t(".delete"), faq_path(faq), class: %i[btn btn-danger],
                  data: { turbo_method: :delete, turbo_confirm: t(".delete_confirm") } %>
    <% end %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1><%= t ".title" %></h1>

<%= render "form", faq: @faq %>

<br>

<div>
  <%= link_to t("faqs.back"), faqs_path %>
</div>

app/views/faqs/index.html.erb
<h1><%= t ".title" %></h1>

<% if admin_signed_in? %>
  <p>
    <%= link_to new_faq_path, class: %i[btn btn-primary] do %>
      <%= fa_icon "plus" %>
      <%= t ".new" %>
    <% end %>
  </p>
<% end %>

<div class="accordion" id="faqs" data-controller="sortable" data-sortable-handle-value=".sortable-handle">
  <%= render @faqs %>
</div>

app/views/faqs/new.html.erb
<h1><%= t ".title" %></h1>

<%= render "form", faq: @faq %>

<br>

<div>
  <%= link_to t("faqs.back"), faqs_path %>
</div>