config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :seasons
  devise_for :admins, controllers: { omniauth_callbacks: "omniauth" }
  devise_scope :admin do
    get "sign_in", to: "auth#sign_in", as: :new_admin_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_admin_session
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  PagesController::PAGES.each do |path|
    get path.dasherize, to: "pages##{path}", as: path.to_sym
  end

  get "admin", to: "admin#index", as: :admin

  resources :bike_rentals, except: :show do
    member { patch :move }
  end
  resources :carousels, only: %i[index show]
  resources :faqs, except: :show do
    member { patch :move }
  end
  resources :galleries
  resources :guides, except: :show do
    member { patch :move }
  end
  resources :page_text, only: :update
  resources :partners do
    member { patch :move }
  end
  resources :photos, except: %i[index show] do
    member { patch :move }
  end
  resources :testimonials, except: :show do
    member { patch :move }
  end

  # redirects
  get "bike-rental", to: redirect("/bike_rentals")
  get "login", to: redirect("/sign_in")
end

app/models/carousel.rb
# frozen_string_literal: true

class Carousel < ApplicationRecord
  audited

  PHOTO_WIDTH = nil
  PHOTO_HEIGHT = 400

  has_many :photos, as: :photoable, dependent: :destroy

  validates :reference, presence: true

  scope :ordered, -> { order reference: :asc }

  def name
    reference.humanize.titleize
  end
end

app/controllers/carousels_controller.rb
# frozen_string_literal: true

class CarouselsController < ApplicationController
  before_action :set_carousel, only: %i[show]

  before_action :authenticate_admin!

  def index
    @carousels = Carousel.ordered
  end

  def show; end

  private

  def set_carousel
    @carousel = Carousel.find(params[:id])
  end
end

app/helpers/carousels_helper.rb
# frozen_string_literal: true

# Helpers for showing carousels
module CarouselsHelper
  def carousel(reference)
    carousel = Carousel.find_by(reference:)
    carousel ||= Carousel.create(reference:)

    render partial: "carousels/carousel", locals: { carousel: }
  end
end

app/views/carousels/_carousel.html.erb
<div id="<%= dom_id carousel %>" class="carousel slide mb-3" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <% carousel.photos.each_with_index do |_, index| %>
      <button type="button" data-bs-target="#<%= dom_id carousel %>" data-bs-slide-to="<%= index %>"
              <% if index == 0 %>
              class="active" aria-current="true"
              <% end %>
              aria-label="Slide <%= (index + 1) %>"></button>
    <% end %>
  </div>
  <div class="carousel-inner">
    <% carousel.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= index.zero? ? "active" : "" %>">
        <%= image_tag url_for(photo.photo), class: %i[d-block mx-auto img-fluid], alt: photo.alt %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#<%= dom_id carousel %>" data-bs-slide="prev">
    <span class="fas fa-2xl fa-chevron-left carousel-chevron-left" title="Previous"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#<%= dom_id carousel %>" data-bs-slide="next">
    <span class="fas fa-2xl fa-chevron-right carousel-chevron-right" title="Next"></span>
  </button>
</div>

<% if admin_signed_in? %>
  <p>
    <%= link_to carousel_path(carousel), class: %i[btn btn-secondary] do %>
      <%= fa_icon "edit" %>
      <%= t ".edit" %>
    <% end %>
  </p>
<% end %>

app/views/carousels/index.html.erb
<h1><%= t ".title" %></h1>

<ul id="carousels" class="list-group">
  <% @carousels.each do |carousel| %>
  <li class="list-group-item">
    <%= link_to carousel.name, carousel_path(carousel) %>
  </li>
  <% end %>
</ul>

app/views/carousels/show.html.erb
<h1><%= link_to t("carousels.index.title"), carousels_path %></h1>

<h2><%= @carousel.name %></h2>

<div class="mb-2">
  <%= link_to new_photo_path(target: @carousel.to_global_id),
              data: { turbo_frame: "modal" },
              class: %i[btn btn-primary] do %>
    <%= fa_icon "plus" %>
    <%= t "photos.add" %>
  <% end %>
</div>

<%= render "photos/list", photos: @carousel.photos, target: @carousel %>