config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :seasons
  devise_for :admins, controllers: { omniauth_callbacks: "omniauth" }
  devise_scope :admin do
    get "sign_in", to: "auth#sign_in", as: :new_admin_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_admin_session
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  PagesController::PAGES.each do |path|
    get path.dasherize, to: "pages##{path}", as: path.to_sym
  end

  get "admin", to: "admin#index", as: :admin

  resources :bike_rentals, except: :show do
    member { patch :move }
  end
  resources :carousels, only: %i[index show]
  resources :faqs, except: :show do
    member { patch :move }
  end
  resources :galleries
  resources :guides, except: :show do
    member { patch :move }
  end
  resources :page_text, only: :update
  resources :partners do
    member { patch :move }
  end
  resources :photos, except: %i[index show] do
    member { patch :move }
  end
  resources :testimonials, except: :show do
    member { patch :move }
  end

  # redirects
  get "bike-rental", to: redirect("/bike_rentals")
  get "login", to: redirect("/sign_in")
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :load_partners
  before_action :turbo_frame_request_variant

  private

  def load_partners
    @partners = Partner.ordered
  end

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# General application-level helpers
module ApplicationHelper
  def fa_icon(name, fa_style = "fa-solid", **html_options)
    classes = [fa_style, "fa-#{name}"]
    classes << "fa-fw" unless html_options.key? :no_fw
    classes += Array(html_options[:class]) if html_options.key? :class
    html_options[:class] = classes.join " "

    content_tag :span, nil, html_options
  end
end

app/views/application/_admin.html.erb
<div class="row row-cols-1">
  <div class="col">
    <div class="card mb-3 p-2 bg-primary-subtle text-primary-emphasis">
      <div class="container">
        <div class="row align-items-center">
          <div class="col">
            <%= t ".logged_in", user: current_admin.email %>
          </div>
          <div class="col">
            <%= button_to t(".logout"), destroy_admin_session_path, method: :get, class: %w[btn btn-primary float-end] %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_footer.html.erb
<div class="footer mt-auto py-3">
  <div class="container">
    <footer>
      <% if admin_signed_in? %>
        <%= render "admin" %>
      <% end %>

      <%== render "partners" %>

      <div class="row row-cols-1">
        <div class="col">
          <div class="card mb-3">
            <div class="card-body text-center">
              <%= link_to "https://www.facebook.com/groups/2431275356936386/", class: %w[btn btn-lg text-white],
                          style: "background-color: #0a53be" do %>
                <%= fa_icon("facebook-f", "fa-brands", title: t(".facebook")) %>
              <% end %>
              <%= link_to "https://twitter.com/ciclosmajor1", class: %w[btn btn-lg text-white],
                          style: "background-color: rgb(85, 172, 238)" do %>
                <%= fa_icon("twitter", "fa-brands", title: t(".twitter")) %>
              <% end %>
              <%= link_to "https://twitter.com/www.instagram.com/ciclos_major_/", class: %w[btn btn-lg text-white],
                          style: "background-color: rgb(172, 43, 172)" do %>
                <%= fa_icon "instagram", "fa-brands", title: t(".instagram") %>
              <% end %>
              <%= mail_to "info@ciclosmajor.com", class: %w[btn btn-lg btn-primary] do %>
                <%= fa_icon("envelope", title: t(".email")) %>
              <% end %>
              <%= link_to "tel:00447557688309", class: %w[btn btn-lg btn-primary] do %>
                <%= fa_icon("phone", title: t(".phone")) %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="row row-cols-1 row-cols-sm-2">
        <div class="col">
          <div class="card mb-3">
            <div class="card-header">
              <%= fa_icon "phone" %>
              <%= t ".call_us" %>
            </div>
            <div class="list-group list-group-flush">
              <%= link_to "tel:00447557688309", class: %w[list-group-item list-group-item-action] do %>
                <span class="fi fi-gb"></span> 00 44 7557 688309
              <% end %>
              <%= link_to "tel:0031650228175", class: %w[list-group-item list-group-item-action] do %>
                <span class="fi fi-nl"></span> 00 31 6 5022 8175
              <% end %>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card mb-3">
            <div class="list-group list-group-flush">
              <%= link_to t(".privacy"), privacy_policy_path, class: %i[list-group-item list-group-item-action] %>
              <%= link_to t(".ts_cs"), terms_and_conditions_path, class: %i[list-group-item list-group-item-action] %>
              <%= link_to Faq.model_name.human(count: 2), faqs_path, class: %i[list-group-item list-group-item-action] %>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/application/_navbar.html.erb
<div class="navbar navbar-expand-lg text-white">
  <div class="container justify-content-center">
    <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <%= fa_icon "bars", class: "text-white" %>
    </button>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <li class="nav-item">
        <%= link_to t(".home"), root_path, class: %i[nav-link active] %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t ".camps" %>
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="/camps/cycling-and-triathlon"><%= t ".cycling_and_tri" %></a></li>
          <li><a class="dropdown-item" href="/camps/bespoke"><%= t ".bespoke_camps" %></a></li>
          <li><a class="dropdown-item" href="/camps/312"><%= t ".312" %></a></li>
        </ul>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t ".hotels" %>
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="/hotels/zafiro-tropic"><%= t ".zafiro_tropic" %></a></li>
          <li><a class="dropdown-item" href="/hotels/zafiro-palace"><%= t ".zafiro_palace" %></a></li>
          <li><a class="dropdown-item" href="/hotels/can-ribera"><%= t ".can_ribera" %></a></li>
          <li><a class="dropdown-item" href="/arrivals-and-transfers"><%= t ".arrivals" %></a></li>
          <li><a class="dropdown-item" href="/locations/mallorca"><%= t ".mallorca" %></a></li>
          <li><a class="dropdown-item" href="/locations/alcudia"><%= t ".alcudia" %></a></li>
          <li><a class="dropdown-item" href="/locations/muro"><%= t ".muro" %></a></li>
          <li><a class="dropdown-item" href="/locations/climate"><%= t ".climate" %></a></li>
        </ul>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t ".ride_groups_and_routes" %>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to t("pages.ride_groups.title"), ride_groups_path, class: :"dropdown-item" %></li>
          <li><%= link_to t(".routes"), routes_path, class: :"dropdown-item" %></li>
          <li><%= link_to t(".lunch_stops"), lunch_stops_path, class: :"dropdown-item" %></li>
          <li><%= link_to t(".safety"), safety_path, class: :"dropdown-item" %></li>
        </ul>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="<%= bike_rentals_path %>"><%= t ".bike_rental" %></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t ".about_us" %>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to t(".about_us"), about_us_path, class: :"dropdown-item" %></li>
          <li><a class="dropdown-item" href="/guides"><%= t ".guides" %></a></li>
        </ul>
      </li>

      <li class="nav-item">
        <%= link_to t(".gallery"), galleries_path, class: :"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to t("pages.videos.title"), videos_path, class: :"nav-link" %>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/testimonials"><%= t ".testimonials" %></a>
      </li>

      <li class="nav-item">
        <%= link_to t(".contact_us"), contact_us_path, class: :"nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/application/_partners.html.erb
<div class="row row-cols-1 row-cols-lg-2" id="partners-links">
  <% @partners.each_slice(2) do |partners| %>
    <div class="col">
      <% partners.each do |partner| %>
        <%= link_to partner_path(partner), data: { turbo_frame: "modal" } do %>
          <%= image_tag partner.logo, alt: partner.name %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>