config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :seasons
  devise_for :admins, controllers: { omniauth_callbacks: "omniauth" }
  devise_scope :admin do
    get "sign_in", to: "auth#sign_in", as: :new_admin_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_admin_session
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  PagesController::PAGES.each do |path|
    get path.dasherize, to: "pages##{path}", as: path.to_sym
  end

  get "admin", to: "admin#index", as: :admin

  resources :bike_rentals, except: :show do
    member { patch :move }
  end
  resources :carousels, only: %i[index show]
  resources :faqs, except: :show do
    member { patch :move }
  end
  resources :galleries
  resources :guides, except: :show do
    member { patch :move }
  end
  resources :page_text, only: :update
  resources :partners do
    member { patch :move }
  end
  resources :photos, except: %i[index show] do
    member { patch :move }
  end
  resources :testimonials, except: :show do
    member { patch :move }
  end

  # redirects
  get "bike-rental", to: redirect("/bike_rentals")
  get "login", to: redirect("/sign_in")
end

app/models/testimonial.rb
# frozen_string_literal: true

class Testimonial < ApplicationRecord
  acts_as_list top_of_list: 0, add_new_at: :top
  audited

  validates :title, presence: true
  validates :text, presence: true

  scope :ordered, -> { order :position }
end

app/controllers/testimonials_controller.rb
# frozen_string_literal: true

class TestimonialsController < ApplicationController
  include Moveable

  before_action :authenticate_admin!, except: :index
  before_action :set_testimonial, only: %i[edit update destroy move]

  def index
    @testimonials = Testimonial.ordered
  end

  def new
    @testimonial = Testimonial.new
  end

  def edit; end

  def create
    @testimonial = Testimonial.new(testimonial_params)

    if @testimonial.save
      redirect_to testimonials_path, notice: t(".success")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @testimonial.update(testimonial_params)
      redirect_to testimonials_path, notice: t(".success"), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @testimonial.destroy!

    redirect_to testimonials_path, notice: t(".success"), status: :see_other
  end

  def move
    super(@testimonial)
  end

  private

  def set_testimonial
    @testimonial = Testimonial.find params[:id]
  end

  def testimonial_params
    params.expect(testimonial: %i[title text])
  end
end

app/views/testimonials/_form.html.erb
<%= bootstrap_form_with(model: testimonial, data: { controller: :tinymce }) do |form| %>
  <% if testimonial.errors.any? %>
    <div style="color: red">
      <h2><%= t ".errors", count: testimonial.errors.count %></h2>

      <ul>
        <% testimonial.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :title %>
  <%= form.text_area :text, data: { tinymce_target: :input }, required: false %>

  <div>
    <%= form.submit %>
    <% if testimonial.persisted? %>
      <%= link_to t(".delete"), testimonial_path(testimonial), class: %i[btn btn-danger],
                  data: { turbo_method: :delete, turbo_confirm: t(".delete_confirm") } %>
    <% end %>
  </div>
<% end %>

app/views/testimonials/_testimonial.html.erb
<div id="<%= dom_id testimonial %>" data-sortable-url="<%= move_testimonial_path testimonial %>">
  <h4>
    <% if admin_signed_in? %>
      <%= fa_icon "grip-lines", class: "me-2 sortable-handle" %>
    <% end %>
    <%= testimonial.title %>
  </h4>
  <p><%= sanitize testimonial.text %></p>
  <% if admin_signed_in? %>
    <p>
      <%= link_to edit_testimonial_path(testimonial), class: %i[btn btn-secondary] do %>
        <%= fa_icon "pencil" %>
        <%= t ".edit" %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/testimonials/edit.html.erb
<h1><%= t ".title" %></h1>

<%= render "form", testimonial: @testimonial %>

<br>

<div>
  <%= link_to t("testimonials.back"), testimonials_path %>
</div>

app/views/testimonials/index.html.erb
<h1><%= t ".title" %></h1>

<% if admin_signed_in? %>
  <p>
    <%= link_to new_testimonial_path, class: %i[btn btn-primary] do %>
      <%= fa_icon "plus" %>
      <%= t ".new" %>
    <% end %>
  </p>
<% end %>

<div id="testimonials" data-controller="sortable" data-sortable-handle-value=".sortable-handle">
  <%= render @testimonials %>
</div>

app/views/testimonials/new.html.erb
<h1><%= t ".title" %></h1>

<%= render "form", testimonial: @testimonial %>

<br>

<div>
  <%= link_to t("testimonials.back"), testimonials_path %>
</div>